# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180930_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], default='Bug', max_length=7),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')], default='ToDo', max_length=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
